---
name: Feature Request
description: Suggest a new feature / parser.
title: '[Feature Request]: '
labels: ['Type: Enhancement']
body:
  - type: markdown
    attributes:
      value: |
        *Please add an appropriate title for this feature request.*

        Before reporting, search for existing [feature requests](https://github.com/kitsumed/SubtitlesParserV2/issues).
        Validate that you are using an up-to-date version, your featyre might already exist!
  - type: checkboxes
    attributes:
      label: Checklist
      description: Make sure you've checked (and actually did) all of the below.
      options:
        - label: I am using an up-to-date version.
          required: true
        - label: I have searched existing [feature requests](https://github.com/kitsumed/SubtitlesParserV2/issues).
          required: true
  - type: textarea
    attributes:
      label: Description
      description: Clear and concise description of the parser/file format you want or missing capability. Attach screenshots if needed, and explain your own use case (with small code snippets if possible).
      placeholder: |
        Description here.
        Code snippet format:
        ```c#
        // Sampe of a short code snippet box.
        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: Sources
      description: Links to any sources that can help us understand the feature request. This can be urls to a the file format docs, wikipedia, etc. Samples files if possible too.